### PR TITLE
Update Embassy, to new PIO API.

### PR DESCRIPTION
**Pull request by Dirbaio**
I've been unable to get 100Mhz to work. I have no idea why. It worked fine before the update. Any help would be appreciated :dizzy_face:

### CODE REVIEW

**Comment by kbleeke** [comment]
Getting to x0140 was a lot of trial and error with the nops. But I never saw these random corruptions. Before, it was always consistently wrong, like just missing the first bit or something.

Idk why an API change like this would mess this up... I also see that you only need one nop now, before I needed two nops for 0x0200. These same setting (1 nop, clkdiv 0x0200) does not work on master. Weird.

It might be fine to just leave it like this, considering pio-sdk also uses this setting. I don't see a difference in startup time (until IP address) for me. I haven't done any throughput measurement, though.

**Comment by Dirbaio** [comment]
> I also see that you only need one nop now, before I needed two nops for 0x0200. These same setting (1 nop, clkdiv 0x0200) does not work on master. Weird.

Yeah, I noticed that too. Wtf! Super weird. Perhaps you have some insights @pennae? 

I have the feeling PIO's '100MHz" is not supposed to work though. The fractional divider works by introducing jitter: it'll do some clock cycles at 125Mhz and others at 62.5Mhz, so that it averages out at 100Mhz. The CYW43 probably requires every single clock cycle to be slower than 100Mhz though, so the fast ones are technically violating the spec. That's probably why pico-sdk did 62.5Mhz. 

I did do bandwidth tests (shoving data as fast as possible up/down through a TCP conn). 100Mhz is slightly faster:

```
// 100mhz
INFO  device         > 14.315519 download: 767 kB/s
INFO  device         > 17.318886 upload: 892 kB/s

// 62.5mhz
INFO  device         > 14.321721 download: 719 kB/s
INFO  device         > 17.325072 upload: 846 kB/s
```

This is when running from RAM. When running from flash the results are lower due to XIP slowness.

I'd say if we can't get 100Mhz working then we should settle for 62.5, yes... If pico-sdk didn't do 100Mhz there must be a reason.

**Comment by kbleeke** [comment]
I have these pin settings all from https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_cyw43_driver/cyw43_bus_pio_spi.c#L139 here as well

**Comment by kbleeke** [comment]
Oh wow, now it makes sense why slower speeds need fewer nops. Thanks for the explanation. 

And yes, with `pin_io.set_input_sync_bypass(false);` it works again for me.

**Comment by Dirbaio** [comment]
Found it. The old code sampled on falling edge, but we're supposed to sample on rising edge. The accidentally-enabled input sync delayed it 2 cycles (so, 1 pio cycle) until falling edge, so it happened to work exactly for 62.5mhz. 100mhz worked by accident I guess? 

Sampling on rising edge works at all speeds.

I've changed the overclock to 125mhz (if we're going to violate the spec on some clock cycles, we might as well violate them in all.), and gated it behind an `overclock` Cargo feature.

**Comment by kbleeke** [comment]
Just to confirm. overclock also works on my device. 

As far as I understand how this all works now, the 2 sysclk time for input sampling time extended over the next rising edge. So with enough "strange nops", this somehow worked. 

I'm glad this now seems to work properly.

**Pull request merged**
