### PR TITLE
Introduce IoctlType enum for IOCTL types

### PR DESCRIPTION
**Pull request by danbev**
This commit introduces an enum to represent the IOCTL command types
available, the direction of the data transfer (Get and Set).

### CODE REVIEW

**Comment by Dirbaio** [comment]
The `enum IoctlHeader` naming is a bit weird: this is not a header, it's just a field within a header.

Also I'm not sure the names for the values are right? WHD calls it the "type", and the values are 0x00 = get, 0x02 = set. https://github.com/Infineon/wifi-host-driver/blob/master/WiFi_Host_Driver/src/include/whd_cdc_bdc.h#L55

**Comment by danbev** [comment]
> The `enum IoctlHeader` naming is a bit weird: this is not a header, it's just a field within a header.

Yeah, I went back and forth on that, I had it named `IoctlHeaderType` but changed it for some reason. 



> Also I'm not sure the names for the values are right?

Hmm, I thought I had got those right but let me take another look and see if I've made a mistake. Thanks

**Review by Dirbaio — APPROVED** [review]
Thanks!

**Comment by danbev** [comment]
@Dirbaio Sorry about this, I had a look and I completely messed this up and confused it with the ioctl channel type :disappointed:

**Pull request merged**
